### ISSUE TITLE
关于文件中part1, part2的疑问

### ISSUE THREAD

**Issue by tzhu-bio** [yuyun-zhang/hexa_dap#1]
您好，请问一下你们上传的bw和bed文件中的part1， part2代表什么呢？

![image](https://user-images.githubusercontent.com/54537420/206168677-bd36ecca-bf8f-46c4-b8bd-ff3e9d4ce673.png)

另外，你们提供的genome browser好像不是全基因组的信息，比如 chr2B:782958294 - 782961638就无法定位？

谢谢~

**Comment by yuyun-zhang** [comment]
@tzhu-bio 您好！因小麦染色体太大，分析时许多软件不能运行成功，为了方便分析，染色体被拆分成了两部分，分别是part1和part2，拆分版本的基因组可以在小麦联盟官方网站上下载（https://urgi.versailles.inra.fr/download/iwgsc/IWGSC_RefSeq_Assemblies/v1.0/iwgsc_refseqv1.0_all_chromosomes.zip）
拆分的断点为：
`chr1A_part1: 471304005;
chr1B_part1: 438720154;
chr1D_part1: 452179604;
chr2A_part1: 462376173;
chr2B_part1: 453218924;
chr2D_part1: 462216879;
chr3A_part1: 454103970;
chr3B_part1: 448155269;
chr3D_part1: 476235359;
chr4A_part1: 452555092;
chr4B_part1: 451014251;
chr4D_part1: 451004620;
chr5A_part1: 453230519;
chr5B_part1: 451372872;
chr5D_part1: 451901030;
chr6A_part1: 452440856;
chr6B_part1: 452077197;
chr6D_part1: 450509124;
chr7A_part1: 450046986;
chr7B_part1: 453822637;
chr7D_part1: 453812268;
`
genome browser中的参考基因组也是拆分版本，查询定位需要根据以上断点转换为part形式

**Comment by tzhu-bio** [comment]
好的，感谢您的解答！

**Comment by yuyun-zhang** [comment]
不客气！
